# Check the tensorflow version

In [2]:
import tensorflow as tf # import tensorflow and name it as tf for now
print(tf.__version__) # print the tensorflow version

2.15.0


In [20]:
import os
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # Will show the error messages but the executor information would be hidden. It is optional

import tensorflow as tf

# for discrete GPU
# physical_devices = tf.config.list_physical_devices('GPU')
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

# Initialization of Tensors
x = tf.constant(4) # tf.Tensor(4, shape=(), dtype=int32)
print(x)

y = tf.constant(4.0)
print(y) # tf.Tensor(4.0, shape=(), dtype=float32)

z = tf.constant(4, shape = (1,1))
print(z) # tf.Tensor([[4]], shape=(1, 1), dtype=int32)

b = tf.constant(4, shape = (1, 1), dtype = tf.float32)
print(b) # tf.Tensor([[4.]], shape=(1, 1), dtype=float32)



# Creating a Matrix (a 2D Tensor)
x = tf.constant([[1, 2, 3], [4, 5, 6]]) # we can also specify the shape here
print(x)

# Output of that 2x3 matrix is below
# tf.Tensor(
# [[1 2 3]
#  [4 5 6]], shape=(2, 3), dtype=int32)


# a 3x3 matrix with values of 1
x = tf.ones((3,3))
print(x)

# Output of the matrix
# tf.Tensor(
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]], shape=(3, 3), dtype=float32)


# a 2x3 matrix with values of 0
x = tf.zeros((2,3))
print(x)

# Output of the matrix
# tf.Tensor(
# [[0. 0. 0.]
#  [0. 0. 0.]], shape=(2, 3), dtype=float32)

h = tf.eye(3) # I for the identity matrix (eye). We can also specify the dtype
print(h)

# Output
# tf.Tensor(
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]], shape=(3, 3), dtype=float32)




# Standard Normal Distribution
k = tf.random.normal((3,3), mean=0, stddev=1)
print(k)

# Output
# [[-0.6938308  -1.462849    0.55938244]
#  [ 0.58626497 -1.1887844  -0.36667934]
#  [-1.0429536   1.3320532   0.668313  ]], shape=(3, 3), dtype=float32)




# Uniform distribution
j = tf.random.uniform((1,3), minval=0, maxval=1)
print(j)

# Output
# tf.Tensor(
# [[ 0.6980954  -3.5213332  -0.5477227 ]
#  [-1.2907193  -0.25775036  2.2616775 ]
#  [ 0.75521404  1.6616408   1.4914474 ]], shape=(3, 3), dtype=float32)
# tf.Tensor([[0.6406189  0.06054878 0.524866  ]], shape=(1, 3), dtype=float32)



# similar to python range function
x = tf.range(9)
print(x) # we will get a vector starting at 0 upto 9 but not 9

# Output: tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


# range(start. limit, delta) delta is the step
x = tf.range(start=1, limit=10, delta=2)
print(x) 

# Output: tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


# Casting to other datatype
x = tf.cast(x, dtype=tf.float64) # tf.float(16,32,64), tf.int(8,16,32,64), tf.bool
print(x)

# Output: tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


# Mathematical Operations

x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = tf.add(x, y)
print(z) # tf.Tensor([10 10 10], shape=(3,), dtype=int32)

z = x + y
print(z) # tf.Tensor([10 10 10], shape=(3,), dtype=int32)

z = tf.subtract(x, y)
print(z) # tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)

z = x - y
print(z) # tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


z = tf.divide(x, y)
print(z) # tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)

z = x / y;
print(z) # tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


z = tf.multiply(x, y)
print(z) # tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)

z = x * y
print(z) # tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)



# DOT product

z = tf.tensordot(x, y, axes = 1)
print(z) # tf.Tensor(46, shape=(), dtype=int32)

# or, for DOT product
z = tf.reduce_sum(x * y, axis = 0)
print(z) # tf.Tensor(46, shape=(), dtype=int32)


# element wise exponentiation

z = x ** 5
print(z) # tf.Tensor([  1  32 243], shape=(3,), dtype=int32)

# Matrix Multiplication

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)

# tf.Tensor(
# [[ 4.869479   -1.9286655   1.7722294  -3.213615  ]
#  [-0.16626382 -0.75633574  2.1167607  -1.1447316 ]], shape=(2, 4), dtype=float32)


# or, for matrix multiplication
z = x @ y
print(z)


# tf.Tensor(
# [[ 3.688439    1.4859405  -1.8079532   2.8155458 ]
#  [ 0.9350849   0.60933113 -0.52185947  0.7227433 ]], shape=(2, 4), dtype=float32)


# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:]) # printing all the element of x: tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)

print(x[1:]) # printing everything except the first one tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)

print(x[1:3]) # non exclusive the 3rd index: tf.Tensor([1 1], shape=(2,), dtype=int32)

print(x[::2]) # skipping: tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)

print(x[::-1]) # printing in the reverse order: tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind) # tf.Tensor([0 2], shape=(2,), dtype=int32)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0]) # tf.Tensor([1 2], shape=(2,), dtype=int32)

print(x[0, :]) # tf.Tensor([1 2], shape=(2,), dtype=int32)

print(x[0:2, :]) 

# tf.Tensor(
# [[1 2]
#  [3 4]], shape=(2, 2), dtype=int32)









# Reshaping

x = tf.range(9)
print(x) # tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)

x = tf.reshape(x, (3, 3))
print(x)

# tf.Tensor(
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]], shape=(3, 3), dtype=int32)



# Transpose

x = tf.transpose(x, perm=[1, 0])
print(x)

# tf.Tensor(
# [[0 3 6]
#  [1 4 7]
#  [2 5 8]], shape=(3, 3), dtype=int32)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.46115416 -1.6405731  -0.6418962 ]
 [ 0.9681658   0.6893051   0.1922664 ]
 [ 1.070468   -1.1577827  -0.66234416]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.28703713 0.7279273  0.50739837]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 